language: nix
sudo: true
install:
- cat /etc/nix/nix.conf || true > ~/nix.conf
- echo "binary-caches = https://cache.nixos.org https://hydra.iohk.io" >> ~/nix.conf
- echo "binary-cache-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=
  cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=" >> ~/nix.conf
- export NIX_CONF_DIR=~
# https://github.com/NixOS/nixops/issues/693
- export BOTO_CONFIG=/dev/null
script:
- travis_wait 30 sleep 1800 &
- "./scripts/travis.sh"
notifications:
  email: false
  slack:
    secure: X1Y5MxPbx0S6Quy1DhT8rUj+GJEOW759EpFrU1Vp2+Zfs/07HKrZv5tJQ04ikuPbnrc3xgCNUc3wgiE+yEhzfDpo64KiyjvOvFMBL530rZoeZYWOTi5/+Sg/EO1/OoaWM+3viIyzqrA+C+QSQVWsFD9ajetfGhXZQsoAjwyDcqRBaOB8uZTnwET0R0u7Y+PNBMrc9dhMMiy6OU9CZtoJDWr7jBrooh43/k3D1PaVZN46j5nVhwcHl56kWmlaANAmSWf8q9ThCQIxRBubrgMJHLk1ysRV5gI2Twb0ChmtqdJRUb7b2div9xhbNT85ypjwSorU1Yhe3XuGlltEJLDGbaFkWLtsV+GOVJt94DhGoZUyJ+vcjfWsXLyGqY3gaYXtp+GViPtyciHCxDi/KE6/jtjTK2C1+kaybz2H/Svl6G/gnwH14LWliItrwOf6YWVyDs7M8OnflFiuDehbFBEjez0roQsAAi/bDdB7WOHj/+4jvmsk79GCtVPTX1qERns9trdNYGTL6m8Au4dZ06ntyf/iwBS0B8m/ayEjUoLEr7VsNCa+RYyxWHojWhq/PqbHNp5qhms2AyM5Nz6j904GYJ6+G/pIn1Esiufjs9QaLkm0qU0Ov3UqN8DwlhPwOAuNmLEpAcDEXPaRjMnIsEhutF7DVYvLmgKNuU5XAfDnis0=
