args:
  nodeLimit:
    tag: NixInt
    contents: 14
  accessKeyId:
    tag: NixStr
    contents: cardano-deployer
environment: Production
nixpkgs: 31a956f18c9251064997085fd7732562b1854726
name: iohk-infra
files:
- deployments/keypairs.nix
- deployments/infrastructure.nix
- deployments/infrastructure-env-production.nix
- deployments/infrastructure-target-aws.nix
elements:
- Infra
target: AWS
