##
## ATTENTION with regard to this file:
##
##  1. it is not intended to be used for building things -- only Nix is supported for that purpose
##  2. its only purpose is to facilitate 'intero' working inside nix-shell, and the following content
##     was carefully crafted to that end -- please, don't change it without ensuring that:
##     - 'intero' continues to work inside nix-shell, and
##     - it doesn't have to rebuild Haskell dependencies that nix-shell already provided
##
nix:
  enable: false
system-ghc: true
resolver: ghc-8.0.2
packages:
- '.'
